from typing import Any, Protocol


class RMMiniGridEnv(Protocol):
    def reset(
        self, *, seed: int | None = None, options: dict[str, Any] | None = None
    ) -> tuple[int, dict[str, bool]]: ...
    def step(self, action: int) -> tuple[int, float, bool, bool, dict[str, bool]]: ...
    def close(self) -> None: ...
    def render(self) -> None: ...
